export type AgentKind = "claude" | "codex";

export interface AgentSelectOption {
  value: string;
  label: string;
  description?: string | null;
}

export interface AgentModelOption extends AgentSelectOption {
  supportedEfforts: AgentSelectOption[];
  serviceTiers?: AgentSelectOption[];
  defaultEffort?: string | null;
  defaultServiceTier?: string | null;
  isDefault?: boolean;
}

export interface AgentCapabilities {
  agent: AgentKind;
  models: AgentModelOption[];
  permissionModes: AgentSelectOption[];
  sandboxModes: AgentSelectOption[];
  defaults: {
    model?: string | null;
    effort?: string | null;
    serviceTier?: string | null;
    permissionMode?: string | null;
    sandboxMode?: string | null;
  };
}

export interface SessionListItem {
  id: string;
  cwd: string;
  mtime: string;
  size: number;
  // Which agent backend owns this session. Absent ⇒ "claude" (back-compat:
  // every pre-existing session and wire message defaults to claude).
  agent?: "claude" | "codex";
  // True when this session was spawned by the call-claude / call-codex peer
  // bridge skills (a headless Claude↔Codex peer-review worker), detected from
  // the fixed signature in its first user turn. Tooling artifact, not a real
  // conversation — the sidebar hides these by default. Absent/false otherwise.
  peer?: boolean;
  // True when Codex reports thread_source:"subagent" (or the equivalent
  // source.subagent metadata). This is distinct from an ordinary fork:
  // both may have parentSessionId, but only subagent worker threads are hidden
  // from the normal sidebar by default.
  subagent?: boolean;
  title?: string | null;
  // Where the title came from. "auto" = generated by the auto-titler,
  // "manual" = the user typed it in the rename UI. The frontend renders a
  // tiny marker for "manual" so the user can tell at a glance which rows
  // they curated themselves vs. which were named by the model.
  titleSource?: "auto" | "manual" | null;
  // One-glyph emoji picked by the auto-titler alongside the title. Used as
  // the row's avatar character. Manual-source rows usually don't have one
  // unless they retained an earlier auto-emoji; SessionRow falls back to
  // the title's first letter when this is empty.
  titleEmoji?: string | null;
  parentSessionId?: string | null;
  // "running" | "exited" | "failed" if a claude process is alive (or recently
  // alive) for this session; null/undefined when the backend has no record.
  // Populated from the in-memory processRegistry, so it reflects only this
  // server's children (CLI sessions outside this server show as null).
  status?: "running" | "exited" | "failed" | null;
  // One-line snippet of the most recent meaningful message in the session's
  // jsonl (last assistant text, or last user prompt for brand-new sessions).
  // Whitespace-collapsed and truncated to 80 chars + "…" if longer.
  preview?: string | null;
  // Role that produced `preview`; lets the sidebar distinguish a pending user
  // prompt from an assistant reply without guessing from the text itself.
  previewRole?: "user" | "assistant" | null;
  // ISO timestamp of the record `preview` was extracted from. Frontends should
  // prefer this over `mtime` for the row's right-side time, since file mtime
  // can be touched by sidechain writes that don't represent user-visible
  // activity. Falls back to file mtime if the record had no timestamp field.
  lastTurnAt?: string | null;
  // ISO timestamp of the most recent "boundary event" — i.e. a turn just
  // started (user message arrived) or just ended (claude reached end_turn).
  // Mid-turn assistant chunks and tool_use/tool_result writes do NOT update
  // this. Sidebar sort uses this field so two simultaneously-streaming
  // sessions don't keep swapping positions on every assistant chunk.
  // Initialized from file mtime on backend boot; overwritten by Date.now()
  // on every subsequent transition.
  lastBoundaryAt?: string | null;
  // ISO timestamp of the server-synced "read up to here" watermark — the
  // session's lastTurnAt at the moment it was last opened on ANY device.
  // A session is unread iff lastTurnAt > readAt. Lets a freshly-loaded
  // device clear badges that were already read elsewhere (offline catch-up).
  // Absent ⇒ never read on any device.
  readAt?: string | null;
  // Server-authoritative unread assistant-turn count. Local storage is only a
  // cold-start cache; list hydration replaces it with this global value.
  unreadCount?: number;
}

export interface UserMessageInfo {
  uuid: string;
  parentUuid: string | null;
  type: string;
  text: string;
}

export interface RewindResponse {
  removedRecords: number;
  truncatedBytes: number;
  prefillText: string;
}

export interface ForkResponse {
  newSessionId: string;
  prefillText: string;
}

export interface NewSessionRequest {
  cwd: string;
  prompt: string;
}

export interface PromptRequest {
  prompt: string;
}

export interface ApiError {
  error: string;
  message: string;
}

// === interaction control plane (M2) =========================================
// Backend pushes `interaction-added` when claude fires a control_request that
// needs user input (permission to use a tool, AskUserQuestion).
// Frontend replies with `interaction-respond` (RPC).
// Backend pushes `interaction-removed` when the pending item leaves the map
// for any reason (answered, cancelled, process died, race with peer tab).
//
// AskUserQuestion piggybacks on `can_use_tool` — `toolName === "AskUserQuestion"`
// and the questions live in `input.questions`. Frontend switches UI by toolName.

export type InteractionToolInput = Record<string, unknown>;

export interface InteractionAdded {
  type: "interaction-added";
  sessionId: string;
  requestId: string;
  // CLI's control_request.request.subtype. Always "can_use_tool" in M2;
  // future subtypes (elicitation, hook_callback) error back as unsupported.
  subtype: string;
  // Set when subtype === "can_use_tool". The model wants to call this tool.
  toolName?: string;
  // The tool's input as Claude generated it. For AskUserQuestion, contains
  // `input.questions: [{ question, header, options: [{label, description}], multiSelect }]`.
  input?: InteractionToolInput;
  // The id of the assistant-generated tool_use block this can_use_tool refers
  // to. Lets the FE attach the permission card to its matching tool_use row in
  // the timeline (so it scrolls with the conversation instead of stacking in a
  // fixed bottom strip). Absent for non-can_use_tool subtypes.
  toolUseId?: string;
  // ISO timestamp when backend received the control_request.
  receivedAt: string;
}

export interface InteractionRemoved {
  type: "interaction-removed";
  sessionId: string;
  requestId: string;
  reason: "answered" | "cancelled" | "process_died" | "superseded";
}

// Response from the frontend to a pending interaction. Discriminated by `kind`.
//   allow         — generic tool permission: let claude run it. updatedInput
//                   optional, overrides the input claude proposed.
//   deny          — generic tool permission: refuse with a message the model
//                   will see as the tool_result.
//   ask-answers   — answers to an AskUserQuestion. Backend folds them into
//                   `updatedInput.answers = {question: text}` and responds
//                   with `behavior: allow`. The native AskUserQuestion tool
//                   reads `answers` and produces a normal (no-is_error)
//                   tool_result identical to TUI output.
export type InteractionAnswer =
  | { kind: "allow"; updatedInput?: InteractionToolInput }
  | { kind: "deny"; message: string }
  | {
      kind: "ask-answers";
      // One entry per question in input.questions, in the same order.
      answers: Array<{
        // The label of the option the user picked, or null when they typed Other.
        selectedLabel: string | null;
        // Free-text "Other" — present when the user clicked Other and typed a value.
        otherText?: string;
      }>;
    };

export interface InteractionRespondRequest {
  type: "interaction-respond";
  sessionId: string;
  requestId: string;
  answer: InteractionAnswer;
}

// === per-session model / permission settings ================================
// Backend pushes `session-settings` (also in GlobalEvent for the global channel
// envelope) when a session's effective model or permissionMode changes —
// either because the user set an override via set-model / set-permission-mode,
// or because the CLI confirmed a change via wire events (system/init,
// system/status). Either field is null when nothing is known yet on either side.

export interface SessionSettingsPush {
  type: "session-settings";
  id: string;
  model: string | null;
  effort: string | null;
  serviceTier: string | null;
  permissionMode: string | null;
}

export interface SetModelRequest {
  type: "set-model";
  sessionId: string;
  // Empty string = clear override and fall back to global default. Free-form
  // string; the backend forwards verbatim to the CLI.
  model: string;
}

export interface SetPermissionModeRequest {
  type: "set-permission-mode";
  sessionId: string;
  // Empty string = clear override. Otherwise must be one of PERMISSION_MODES
  // from prefs.ts; backend rejects unknowns with 400.
  mode: string;
}

export interface SetServiceTierRequest {
  type: "set-service-tier";
  sessionId: string;
  // Empty string clears the override. "priority" is the Codex catalog tier
  // displayed as Fast in the UI.
  serviceTier: "" | "priority";
}

// === cli-info (read-only slash commands: /mcp, /status, /doctor, …) ==========
// Frontend sends `cli-info` for informational slash commands handled locally;
// backend gathers the answer (claude CLI invocation or config-file reads) and
// returns a markdown blob the frontend renders as a client-side system bubble
// (never sent to the model).

export const CLI_INFO_TOPICS = [
  "mcp",
  "plugin",
  "status",
  "hooks",
  "agents",
  "memory",
  "release-notes",
  "version",
  "doctor",
] as const;
export type CliInfoTopic = typeof CLI_INFO_TOPICS[number];

export interface CliInfoRequest {
  type: "cli-info";
  sessionId: string;
  topic: CliInfoTopic;
}

export interface CliInfoResult {
  title: string;
  markdown: string;
}

export interface CodexRateLimitWindow {
  usedPercent: number;
  windowDurationMins: number | null;
  /** Unix timestamp in seconds, as reported by Codex app-server. */
  resetsAt: number | null;
}

export interface CodexRateLimits {
  planType: string | null;
  primary: CodexRateLimitWindow | null;
  secondary: CodexRateLimitWindow | null;
}

export interface CodexThreadUsageGroup {
  model: string | null;
  reasoningEffort: string | null;
  speed: string | null;
  inputTokens: number | null;
  cachedInputTokens: number | null;
  netNewInputTokens: number | null;
  outputTokens: number | null;
  totalTokens: number | null;
  /** Estimated ChatGPT usage credits, expressed in millionths of one credit. */
  estimatedUsageCreditsMicros: number;
}

export interface CodexThreadUsage {
  threadId: string;
  /** Estimated ChatGPT usage credits, expressed in millionths of one credit. */
  estimatedUsageCreditsMicros: number;
  /** Estimated API-equivalent cost, expressed in millionths of one US dollar. */
  estimatedUsageUsdMicros: number | null;
  groups: CodexThreadUsageGroup[];
}

export interface CodexAccountUsageDailyBucket {
  /** UTC calendar date reported by Codex, normally YYYY-MM-DD. */
  startDate: string;
  tokens: number;
}

export interface CodexUsageOverview {
  threadUsage: CodexThreadUsage | null;
  dailyUsageBuckets: CodexAccountUsageDailyBucket[];
  accountLifetimeTokens: number | null;
}

// === background tasks (subagents / workflows / background shells) ===========
// Backend observes Task/Agent/Workflow tool_use blocks and Bash
// run_in_background launches on the CLI wire, plus their completion
// (<task-notification> user turns). Pushed as `background-tasks` on the
// global channel whenever a session's task list changes; initial load via
// the `get-background-tasks` WS request.

export type BackgroundTaskKind = "agent" | "workflow" | "shell" | "cron";

export interface BackgroundTask {
  // Parsed task id when the launch ack carried one, else the tool_use id.
  taskId: string;
  kind: BackgroundTaskKind;
  // Worker thread ids owned by this lifecycle item. Codex collaboration
  // events expose these directly, which lets the UI correlate the transient
  // app-server event with the durable indexed subagent session.
  relatedSessionIds?: string[];
  // Short human label (agent description, workflow name, or command snippet).
  label: string;
  startedAt: string; // ISO
  status: "running" | "completed" | "failed";
  completedAt?: string; // ISO, present once status leaves "running"
}

export interface BackgroundTasksPush {
  type: "background-tasks";
  sessionId: string;
  tasks: BackgroundTask[];
}

export interface GetBackgroundTasksRequest {
  type: "get-background-tasks";
  sessionId: string;
}

// One entry in the composer slash-command picker. `name` is the exact command
// the provider reported or exposed (already namespaced for plugins, e.g.
// "superpowers:brainstorming"). `description` is best-effort. Codex skills
// also carry `path` so the backend can send a native UserInput skill instead
// of a plain "/skill" text prompt.
export interface SkillEntry {
  name: string;
  description?: string;
  path?: string;
}

export const DEFAULT_FORWARDED_SLASH_COMMANDS = ["compact", "clear"] as const;

export type CodexGoalStatus =
  | "active"
  | "paused"
  | "blocked"
  | "usageLimited"
  | "budgetLimited"
  | "complete";

export interface CodexGoal {
  threadId: string;
  objective: string;
  status: CodexGoalStatus;
  tokenBudget: number | null;
  tokensUsed: number;
  timeUsedSeconds: number;
  createdAt: number;
  updatedAt: number;
}
